-- Seed teams
insert into teams (name) values ('AIK') on conflict (name) do nothing;
insert into teams (name) values ('BK Häcken') on conflict (name) do nothing;
insert into teams (name) values ('BP') on conflict (name) do nothing;
insert into teams (name) values ('Degerfors IF') on conflict (name) do nothing;
insert into teams (name) values ('Djurgården') on conflict (name) do nothing;
insert into teams (name) values ('Gais') on conflict (name) do nothing;
insert into teams (name) values ('Halmstads BK') on conflict (name) do nothing;
insert into teams (name) values ('Hammarby') on conflict (name) do nothing;
insert into teams (name) values ('IF Elfsborg') on conflict (name) do nothing;
insert into teams (name) values ('IFK Göteborg') on conflict (name) do nothing;
insert into teams (name) values ('IK Sirius') on conflict (name) do nothing;
insert into teams (name) values ('Kalmar FF') on conflict (name) do nothing;
insert into teams (name) values ('Malmö FF') on conflict (name) do nothing;
insert into teams (name) values ('Mjällby AIF') on conflict (name) do nothing;
insert into teams (name) values ('Västerås SK') on conflict (name) do nothing;
insert into teams (name) values ('Örgryte IS') on conflict (name) do nothing;

-- Seed rounds
insert into rounds (round_no, dates) values (1, '04/04–06/04') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (2, '11/04–13/04') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (3, '18/04–20/04') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (4, '22/04–23/04') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (5, '25/04–27/04') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (6, '02/05–04/05') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (7, '09/05–11/05') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (8, '16/05–18/05') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (9, '23/05–25/05') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (10, '31/05') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (11, '04/07–06/07') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (12, '11/07–13/07') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (13, '18/07–20/07') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (14, '25/07–27/07') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (15, '01/08–03/08') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (16, '08/08–10/08') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (17, '15/08–17/08') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (18, '22/08–24/08') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (19, '29/08–31/08') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (20, '05/09–07/09') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (21, '12/09–14/09') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (22, '19/09–20/09') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (23, '10/10–12/10') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (24, '17/10–19/10') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (25, '24/10–26/10') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (26, '28/10–29/10') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (27, '31/10–01/11') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (28, '07/11–08/11') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (29, '21/11–24/11') on conflict (round_no) do nothing;
insert into rounds (round_no, dates) values (30, '29/11') on conflict (round_no) do nothing;

-- Seed matches (delete existing first to avoid duplicates)
delete from matches;
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'AIK'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'Gais'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 1), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'BP'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 2), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'AIK'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 3), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Gais'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 4), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'AIK'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'BP'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 5), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Gais'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 6), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'AIK'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 7), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Gais'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'BP'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 8), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 9), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'AIK'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Gais'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 10), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'BP'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 11), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Gais'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'BP'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 12), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'AIK'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 13), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'Gais'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'BP'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 14), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'AIK'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'Gais'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'BP'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 15), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 16), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'Gais'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'BP'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 17), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'AIK'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'BP'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 18), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'AIK'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'Gais'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 19), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Gais'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'BP'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 20), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'AIK'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 21), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'BP'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 22), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'AIK'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'Gais'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 23), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'AIK'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'BP'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 24), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'Gais'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 25), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'AIK'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'BP'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 26), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'Gais'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 27), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'AIK'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'BP'), (select id from teams where name = 'Mjällby AIF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 28), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'AIK'), (select id from teams where name = 'Degerfors IF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'Hammarby'), (select id from teams where name = 'IFK Göteborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'Gais'), (select id from teams where name = 'Västerås SK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'Örgryte IS'), (select id from teams where name = 'Kalmar FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'BK Häcken'), (select id from teams where name = 'IF Elfsborg'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'Mjällby AIF'), (select id from teams where name = 'Malmö FF'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'BP'), (select id from teams where name = 'Halmstads BK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 29), (select id from teams where name = 'IK Sirius'), (select id from teams where name = 'Djurgården'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Djurgården'), (select id from teams where name = 'BK Häcken'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'IFK Göteborg'), (select id from teams where name = 'IK Sirius'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Malmö FF'), (select id from teams where name = 'BP'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'IF Elfsborg'), (select id from teams where name = 'Gais'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Degerfors IF'), (select id from teams where name = 'Örgryte IS'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Västerås SK'), (select id from teams where name = 'Hammarby'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Kalmar FF'), (select id from teams where name = 'AIK'));
insert into matches (round_id, home_team, away_team) values ((select id from rounds where round_no = 30), (select id from teams where name = 'Halmstads BK'), (select id from teams where name = 'Mjällby AIF'));